### ISSUE TITLE
Creating pipes for GWakeup: Too many open files Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by udhay24** [pipeless-ai/pipeless#137]
**Describe the bug**
When i try to open multiple streams i run into too many open files error
**To Reproduce**
Please describe the steps to reproduce the behavior:
1. Run 30 + streams simultaneously on TensorRT runtime with rtsp as input 
2. The GPU usage is around ~35% during period

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 22
 - Tesla T4

**Comment by miguelaeh** [comment]
Hi @udhay24 ,
Does it work if you increase the default limit? 

You can do something like:
```
ulimit -n 2048
```

By default, it is in most cases `1024`

**Comment by udhay24** [comment]
Hi @miguelaeh , 
i tried increasing the ulimit and it fixed the issue. 

Currently I am using a 15Gb ram and 4 VCPU spec, as i approach the 30+ streams. the RAM reaches the limit and it crashes the application.  Do you have a suggested configuration or options i can use to make it efficient

Thanks

**Comment by udhay24** [comment]
Yeah, that fixed the RAM overflow issue
Thanks a lot
