### ISSUE TITLE
[BUG](COMPONENT): Docker init throws PermissionDenied

### ISSUE THREAD

**Issue by stevewells20** [pipeless-ai/pipeless#138]
**Describe the bug**
Following the Container guide.
Running the init command:
`docker run --rm -it -v /home/nvidia/pipeless:/app miguelaeh/pipeless init my_project`
yields:
`
Creating Python virtual env...
thread 'main' panicked at src/cli/init.rs:10:34:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
The /home/nvidia/pipeless folder has been created and had the permissions set with:
`chgrp -R root /home/nvidia/pipeless`

**To Reproduce**
Follow the guide at: https://www.pipeless.ai/docs/docs/v1/container
Every command up until the init ran smoothly.
Interestingly, I'm able to start a pipeless instance successfully:
`docker run --rm -v /your/project/dir:/app miguelaeh/pipeless start --stages-dir /app`

`
Creating Python virtual env...

(pipeless:1): GStreamer-WARNING **: 09:22:28.059: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
[2024-04-09T09:22:31Z INFO  pipeless_ai::stages::parser] ⚙️  Loading stages from /app
[2024-04-09T09:22:31Z INFO  pipeless_ai::config::adapters::rest] REST adapter running
[2024-04-09T09:22:31Z INFO  warp::server] Server::run; addr=0.0.0.0:3030
[2024-04-09T09:22:31Z INFO  warp::server] listening on http://0.0.0.0:3030
`

**Expected behavior**
A pipeless project to be initiated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic Beaver
 - Version: 18.04.3 LTS
-  Processor arch: aarch64 (Jetson Nano)

**Comment by miguelaeh** [comment]
Hi @stevewells20 ,

This is probably because the `init` command creates a directory. Ensure you are adjusting the permissions of the local directory you are mounting to be owned by the `root` group as explained here (in the yellow sections): https://www.pipeless.ai/docs/v1/container#image-usage

**Comment by stevewells20** [comment]
Yes, I've done that.
1) mkdir /home/nvidia/pipeless
2) chgrp -R root /home/nvidia/pipeless
3) docker run --rm -it -v /home/nvidia/pipeless:/app miguelaeh/pipeless init my_project

**Comment by stevewells20** [comment]
Actually... Just did something similar and it worked, but I'm not sure how it is different.

`mkdir pipeless`
`sudo chgrp -R root  /home/nvidia/pipeless/`
`docker run --rm -it -v /home/nvidia/pipeless:/app miguelaeh/pipeless init test`

Well, I must've fat fingered something. Sorry for the trouble; I'm pretty excited to try pipeless out!

**Comment by miguelaeh** [comment]
Glad to hear it worked!

FYI you were able to start the pipeless instance successfully even without creating a project because the start command only reads the directory, so if it reads an empty directory it is fine, just there won't be stages to use.
