### ISSUE TITLE
BUG: Incorrect Hyperlink in Multipose Detection with TensorFlow Example

### ISSUE THREAD

**Issue by Haleshot** [pipeless-ai/pipeless#77]
**Describe the bug**
1. The hyperlink for the "Multipose Detection with TensorFlow" example in the documentation's "Examples" category is pointing to the wrong page, resulting in a 404 Page Not Found error.
2. Additionally, attempting to edit any page on the documentation website using the "Edit this page" link leads to a Not Found page, making it impossible to contribute changes.

**To Reproduce**
1. Navigate to the "Examples" category on the left side of the [docs website](https://www.pipeless.ai/docs/docs/v1/examples).
2. Click on the "Multipose Detection with TensorFlow" hyperlink.
3. Observe the 404 Page Not Found error.
4. Click on the "Edit this page" link for any sub-page on the [documentation website](https://github.com/pipeless-ai/docs/pages/v1/examples/tf-pose.mdx).

**Expected behavior**
1. The hyperlink for "Multipose Detection with TensorFlow" should lead to [https://www.pipeless.ai/docs/docs/v1/examples/tf-pose](https://www.pipeless.ai/docs/docs/v1/examples/tf-pose) instead of [https://www.pipeless.ai/docs/docs/v1/examples/pose](https://www.pipeless.ai/docs/docs/v1/examples/pose).

2. The "Edit this page" link should direct to the corresponding Markdown file for editing, allowing users to contribute changes to the documentation.

**Screenshots**
![404_Error_Page](https://github.com/pipeless-ai/pipeless/assets/57552973/be55d2af-ddc4-4efa-8f06-d5e79eaf9e75)
![Not_Found](https://github.com/pipeless-ai/pipeless/assets/57552973/bde24b67-675e-40c8-b633-b6e34be50c25)

**Desktop:**
- OS: Windows 11
- Version: 23H2
- Processor arch: x86

**Additional context**
- This issue is specific to the "Multipose Detection with TensorFlow" example in the "Examples" category. All other examples in the same category have correct hyperlinks.
- The editing issue is prevalent across all sub-pages, making it impossible to contribute changes to the documentation.

**Comment by Haleshot** [comment]
Sorry, opened the issue in the wrong repository. Raised the issue in the docs repository. Closing the issue now.

**Comment by miguelaeh** [comment]
No worries @Haleshot , I just linked a PR fixing the edit URL.
