### ISSUE TITLE
(EXAMPLES): I'm unable to run examples (watermark and cats).

### ISSUE THREAD

**Issue by MikiGrit** [pipeless-ai/pipeless#81]
**Describe the bug**
I followed tutorials for watermark and cats and it failed to run at the step `pipeless start --stages-dir .`

**To Reproduce**
Please describe the steps to reproduce the behavior:
1. I have installed required libraries (pillow, numpy and opencv-python). They are correctly shown as present when run `pip list`.
2. Run `wget -O - https://github.com/pipeless-ai/pipeless/archive/main.tar.gz | tar -xz --strip=2 "pipeless-main/examples/cats"`
3. Running `pipeless start --stages-dir .` will then give the following output:

```
[2023-11-18T20:24:00Z INFO  pipeless_ai::stages::parser] ⚙️  Loading stages from .
[2023-11-18T20:24:00Z INFO  pipeless_ai::stages::parser] ⏳ Loading stage 'cats' from ./cats
[2023-11-18T20:24:00Z INFO  pipeless_ai::stages::parser]        Loading hook from ./cats/pre-process.py
thread 'main' panicked at src/stages/languages/python.rs:174:15:
Unable to create Python module from hook: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'cv2'"), traceback: Some(<traceback object at 0x7f885cf6f280>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace         
```

**Expected behavior**
It will work without any failures.

**Desktop (please complete the following information):**
- OS: WSL, Ubuntu 22.04
- Processor arch: amd64
- Python: 3.11

Thanks for any suggestions.

**Comment by miguelaeh** [comment]
Hi @MikiGrit ,

Could you share the output of the following commands?
* `pip list`. I read you can see `opencv-python` there, but just to verify since `cv2` is the `opencv-python` package.
* `pip --version`
* `python --version`

Also, did you recently update your python version? May it be possible that your pip installation is linked to a different Python version than `3.11`?

**Comment by MikiGrit** [comment]
Sure, here are the outputs:

pip list
```
Package       Version
------------- --------
numpy         1.26.2
opencv-python 4.8.1.78
Pillow        10.1.0
pip           23.3.1
setuptools    65.5.0 
```

pip --version
```
pip 23.3.1 from /home/krupickam/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/pip (python 3.11)
```

python --version
```
Python 3.11.6
```

**Comment by miguelaeh** [comment]
@MikiGrit I think I have an idea of what is happening, could you please run:
```console copy
ldd $(which pipeless) 
```

and share the output?

It contains a line linking to `libpython`, let's see if the linked version is the version you are actually using. It may happen that you have more than one Python installed

**Comment by MikiGrit** [comment]
You are right. I have more versions of python.

Here is the output:
```
❯ ldd $(which pipeless)
linux-vdso.so.1 (0x00007ffd750e6000)
libonnxruntime.so.1.16.0 => /home/krupickam/.pipeless/libonnxruntime.so.1.16.0 (0x00007fb4ec20a000)
libpython3.10.so.1.0 => /lib/x86_64-linux-gnu/libpython3.10.so.1.0 (0x00007fb4ebc1d000)
libgstapp-1.0.so.0 => /lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007fb4ebc07000)
libgstbase-1.0.so.0 => /lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007fb4ebb82000)
libgstreamer-1.0.so.0 => /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007fb4eba31000)
libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fb4eb9cf000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb4eb895000)
libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fb4eb6bc000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb4eb69c000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb4eb5b5000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb4eb38d000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb4ee07f000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb4eb386000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb4eb381000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb4eb365000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb4eb360000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb4eb134000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb4eb103000)
libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fb4eb0fa000)
libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fb4eb0df000)
libdw.so.1 => /lib/x86_64-linux-gnu/libdw.so.1 (0x00007fb4eb033000)
libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007fb4eb026000)
libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb4eafb0000)
libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fb4eaf6a000)
libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fb4eaf3e000)
liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb4eaf13000)
libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007fb4eaef5000)
libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fb4eaee2000)
libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fb4eaea9000)
libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb4eae12000)
```

It is apparently using the wrong one. Would you know how to fix it?

**Comment by miguelaeh** [comment]
There is the problem, the pipeless installation is linking to verion `3.10` and the installed pip packages are for `3.11`.

You have two options to fix this:

**Option 1:** To continue using Python `3.11`, just execute the pipeless installation script again providing the `--build` . It will build pipeless from source on the fly (maybe request you a couple packages before it can proceed) and it will be linked to your Python version.
**Option 2:** Install the pip packages for Python version `3.10` instead of `3.11`. You probably have Python `3.10` because it comes by default with Ubuntu. Try installting the pip pacakges using `/usr/bin/pip3.10 install <package>`.

**Comment by MikiGrit** [comment]
Ok, thank you for your answers. I did not realized that by installing, I'm binding `pipeless` to certain python version.

**Comment by miguelaeh** [comment]
No problem! That happens because the install uses the pre-built binary by default, unless you provide the `--build` flag. I will clarify that on the docs.

**Comment by Matesanz** [comment]
:point_down:  Even though normally I'm using `pyenv`, for me the solution was installing python using `apt`:

```bash
sudo add-apt-repository ppa:deadsnakes/ppa   
sudo apt-get update
sudo apt-get install libpython3.11-dev
```
